name: Build Wget for Mac M1

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install automake autoconf libtool

    - name: Download Wget source
      run: |
        curl -O http://ftp.gnu.org/gnu/wget/wget-1.9.1.tar.gz

    - name: Extract Wget source
      run: |
        tar zxvf wget-1.9.1.tar.gz

    - name: Build Wget
      run: |
        cd wget-1.9.1
        ./configure
        make

    - name: Install Wget
      run: |
        cd wget-1.9.1
        sudo make install

    - name: Verify Wget installation
      run: |
        wget --version
