name: Build and Release wget for Mac m1

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    if: startsWith(github.event.release.tag, 'v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install autoconf automake libtool

      - name: Configure wget
        run: ./configure

      - name: Build wget
        run: make

      - name: Create release asset
        run: |
          mkdir wget-dist
          cp wget wget-dist/
          tar -czvf wget-m1.tar.gz wget-dist
          rm -rf wget-dist

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: wget-m1.tar.gz
          asset_name: wget-m1.tar.gz
          asset_content_type: application/gzip
