name: Test macOS Environment

on:
  push:
    branches:
      - main

jobs:
  test-macos:
    runs-on: macos-latest

    steps:
      - name: Check Environment
        run: |
          uname -a
          sw_vers