jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install Rosetta
        run: |
          softwareupdate --install-rosetta --agree-to-license

      - name: Configure and Build for x86_64
        run: |
          ./configure --host=x86_64-apple-darwin --build=aarch64-apple-darwin
          make